modLoader="javafml"
loaderVersion="[40,)"
license="MIT license"
issueTrackerURL="https://github.com/Sarinsa/Damp-Soil/issues"

[[mods]]
modId="dampsoil"
version="${file.jarVersion}"
displayName="Damp Soil"
logoFile="logo.png"
credits="RandomMcSomethin (original author)"
authors="Sarinsa"
description='''
Introduces some changes to how farmland works, how crops grow and a couple other things. Also comes with sprinklers for all your sprinkly needs!
'''
[[dependencies.dampsoil]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dampsoil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
