modLoader="javafml"
loaderVersion="[36,)"
license="MIT license"
issueTrackerURL="https://github.com/Sarinsa/Damp-Soil/issues"

[[mods]]
modId="dampsoil"
version="${file.jarVersion}"
displayName="Damp Soil"
logoFile="logo.png"
credits="RandomMcSomethin (original author)"
authors="Sarinsa"
description='''
Introduces some changes to how farmland works, how crops grow and a couple other things. Also comes with sprinklers for all your sprinkly needs!
'''
[[dependencies.dampsoil]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dampsoil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
